import { db } from '@/db';
import { serviceRequests, testbedTasks, statusHistory } from '@/db/schema';

async function main() {
    // Service Requests - 15 records starting from ID 19
    const sampleServiceRequests = [
        // 2 requested (last 3 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-01-01-01`,
            companyId: 3,
            contactPersonId: 5,
            productName: 'Smart IoT Gateway Device',
            productDescription: '5G-enabled IoT gateway with multi-protocol support',
            quantity: 2,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Test under various network load conditions',
            status: 'requested',
            requestedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Urgent request from client',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-02-01-01`,
            companyId: 5,
            contactPersonId: 8,
            productName: 'Industrial Temperature Sensor Array',
            productDescription: 'Multi-point temperature monitoring system for industrial use',
            quantity: 5,
            testType: 'Environmental Testing',
            specialRequirements: 'Test temperature range: -40°C to +85°C',
            status: 'requested',
            requestedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: null,
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 2 replied (last 7-10 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-03-01-01`,
            companyId: 2,
            contactPersonId: 3,
            productName: 'High-Power LED Driver Board',
            productDescription: '100W LED driver with dimming control',
            quantity: 3,
            testType: 'High Voltage Testing',
            specialRequirements: 'Test voltage surge protection up to 2kV',
            status: 'replied',
            requestedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Quotation sent to client',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-04-01-01`,
            companyId: 7,
            contactPersonId: 12,
            productName: 'Wireless Vibration Monitoring System',
            productDescription: 'Battery-powered wireless sensor for machinery monitoring',
            quantity: 10,
            testType: 'Vibration Testing',
            specialRequirements: 'Test frequency range: 10Hz to 10kHz',
            status: 'replied',
            requestedDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Waiting for client confirmation',
            createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 2 srf_filled (last 10-15 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-05-01-01`,
            companyId: 4,
            contactPersonId: 7,
            productName: 'Automotive ECU Control Module',
            productDescription: 'Electronic control unit for vehicle systems',
            quantity: 1,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Automotive standards compliance testing',
            status: 'srf_filled',
            requestedDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'SRF form received and verified',
            createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-06-01-01`,
            companyId: 6,
            contactPersonId: 10,
            productName: 'Medical Grade Power Supply Unit',
            productDescription: '24V 5A medical grade isolated power supply',
            quantity: 4,
            testType: 'High Voltage Testing',
            specialRequirements: 'Medical device safety standards testing',
            status: 'srf_filled',
            requestedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Awaiting pricing approval',
            createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 3 agreed (last 15-20 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-07-01-01`,
            companyId: 1,
            contactPersonId: 2,
            productName: 'Industrial PCB Assembly',
            productDescription: 'Multi-layer PCB for industrial automation',
            quantity: 8,
            testType: 'Environmental Testing',
            specialRequirements: 'Humidity and temperature cycling tests',
            status: 'agreed',
            requestedDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Client agreed to terms, awaiting sample delivery',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-08-01-01`,
            companyId: 8,
            contactPersonId: 14,
            productName: 'RF Communication Module',
            productDescription: '2.4GHz wireless transceiver module',
            quantity: 6,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'RF spectrum analysis and compliance testing',
            status: 'agreed',
            requestedDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Priority testing requested',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-09-01-01`,
            companyId: 3,
            contactPersonId: 6,
            productName: 'Solar Charge Controller',
            productDescription: 'MPPT solar charge controller 48V 60A',
            quantity: 2,
            testType: 'High Voltage Testing',
            specialRequirements: 'Overload and reverse polarity protection testing',
            status: 'agreed',
            requestedDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: null,
            createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 3 material_received (last 20-30 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-10-01-01`,
            companyId: 2,
            contactPersonId: 4,
            productName: 'Smart Metering Device',
            productDescription: 'Three-phase energy meter with IoT connectivity',
            quantity: 3,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Power quality analysis and harmonic testing',
            status: 'material_received',
            requestedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 3,
            assignedTestbedId: null,
            dcNumber: 'DC-2024-0325',
            dcVerified: true,
            notes: 'Samples received and verified against DC',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-11-01-01`,
            companyId: 5,
            contactPersonId: 9,
            productName: 'Pressure Sensor Module',
            productDescription: 'Industrial pressure transducer 0-10 bar',
            quantity: 12,
            testType: 'Environmental Testing',
            specialRequirements: 'Pressure cycling and thermal shock tests',
            status: 'material_received',
            requestedDate: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 5,
            assignedTestbedId: null,
            dcNumber: 'DC-2024-0328',
            dcVerified: true,
            notes: 'All 12 units received in good condition',
            createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-12-01-01`,
            companyId: 7,
            contactPersonId: 13,
            productName: 'Digital Display Controller',
            productDescription: 'TFT display controller with touch interface',
            quantity: 5,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Display EMI and ESD susceptibility testing',
            status: 'material_received',
            requestedDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 7,
            assignedTestbedId: null,
            dcNumber: 'DC-2024-0329',
            dcVerified: true,
            notes: 'Samples with calibration certificates received',
            createdAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 2 testing (last 30-45 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-13-01-01`,
            companyId: 4,
            contactPersonId: 7,
            productName: 'Motor Drive Controller',
            productDescription: 'Variable frequency drive for 3-phase motors',
            quantity: 2,
            testType: 'High Voltage Testing',
            specialRequirements: 'Insulation resistance and high-pot testing',
            status: 'testing',
            requestedDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
            testingStartDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 4,
            assignedTestbedId: 3,
            dcNumber: 'DC-2024-0315',
            dcVerified: true,
            notes: 'Testing in progress on Test Bed 3',
            createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-14-01-01`,
            companyId: 6,
            contactPersonId: 11,
            productName: 'Ultrasonic Distance Sensor',
            productDescription: 'Industrial ultrasonic range finder 0-10m',
            quantity: 15,
            testType: 'Environmental Testing',
            specialRequirements: 'Temperature variation and accuracy testing',
            status: 'testing',
            requestedDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
            testingStartDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 6,
            assignedTestbedId: 5,
            dcNumber: 'DC-2024-0310',
            dcVerified: true,
            notes: 'Environmental chamber testing ongoing',
            createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 1 completed (last 45-60 days)
        {
            jobCardNumber: `ARTL-RF-${new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString().slice(2, 10).replace(/-/g, '')}-15-01-01`,
            companyId: 1,
            contactPersonId: 1,
            productName: 'Bluetooth Low Energy Module',
            productDescription: 'BLE 5.0 wireless module for IoT applications',
            quantity: 20,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Full RF conformance testing suite',
            status: 'completed',
            requestedDate: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
            agreedDate: new Date(Date.now() - 53 * 24 * 60 * 60 * 1000).toISOString(),
            materialReceivedDate: new Date(Date.now() - 51 * 24 * 60 * 60 * 1000).toISOString(),
            testingStartDate: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
            testingEndDate: new Date(Date.now() - 46 * 24 * 60 * 60 * 1000).toISOString(),
            completionDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            assignedEmployeeId: 2,
            assignedTestbedId: 1,
            dcNumber: 'DC-2024-0225',
            dcVerified: true,
            notes: 'All tests completed successfully, report delivered',
            createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(serviceRequests).values(sampleServiceRequests);

    // Testbed Tasks - 23 records
    const sampleTestbedTasks = [
        // Test bed 1: 1 in_progress + 3 queued
        {
            serviceRequestId: 19,
            testbedId: 1,
            assignedEmployeeId: 2,
            status: 'in_progress',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            actualEndDate: null,
            queuePosition: 0,
            notes: 'EMC testing in progress',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 20,
            testbedId: 1,
            assignedEmployeeId: 2,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 1,
            notes: 'Waiting for current test to complete',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 26,
            testbedId: 1,
            assignedEmployeeId: 2,
            status: 'queued',
            priority: 'urgent',
            scheduledStartDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 2,
            notes: 'Priority client request',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 28,
            testbedId: 1,
            assignedEmployeeId: 2,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 3,
            notes: null,
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Test bed 2: 4 queued
        {
            serviceRequestId: 21,
            testbedId: 2,
            assignedEmployeeId: 3,
            status: 'queued',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 1,
            notes: 'Environmental chamber tests scheduled',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 24,
            testbedId: 2,
            assignedEmployeeId: 3,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 2,
            notes: 'Temperature cycling tests',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 27,
            testbedId: 2,
            assignedEmployeeId: 3,
            status: 'queued',
            priority: 'low',
            scheduledStartDate: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 3,
            notes: null,
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 29,
            testbedId: 2,
            assignedEmployeeId: 3,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 4,
            notes: 'Pressure testing scheduled',
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Test bed 3: 1 in_progress + 2 queued
        {
            serviceRequestId: 31,
            testbedId: 3,
            assignedEmployeeId: 4,
            status: 'in_progress',
            priority: 'urgent',
            scheduledStartDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            actualEndDate: null,
            queuePosition: 0,
            notes: 'High voltage testing 50% complete',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 22,
            testbedId: 3,
            assignedEmployeeId: 4,
            status: 'queued',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 1,
            notes: 'LED driver testing',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 25,
            testbedId: 3,
            assignedEmployeeId: 4,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 2,
            notes: 'Solar controller high voltage tests',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Test bed 5: 1 in_progress + 3 queued
        {
            serviceRequestId: 32,
            testbedId: 5,
            assignedEmployeeId: 6,
            status: 'in_progress',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            actualEndDate: null,
            queuePosition: 0,
            notes: 'Environmental testing cycle 2 of 5',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 23,
            testbedId: 5,
            assignedEmployeeId: 6,
            status: 'queued',
            priority: 'urgent',
            scheduledStartDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 1,
            notes: 'Vibration testing - urgent',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 30,
            testbedId: 5,
            assignedEmployeeId: 6,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 2,
            notes: 'Environmental chamber - pressure sensors',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 19,
            testbedId: 5,
            assignedEmployeeId: 6,
            status: 'queued',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 3,
            notes: 'IoT gateway environmental testing',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Test bed 7: 1 in_progress + 2 queued
        {
            serviceRequestId: 30,
            testbedId: 7,
            assignedEmployeeId: 8,
            status: 'in_progress',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            actualEndDate: null,
            queuePosition: 0,
            notes: 'Display controller EMI tests ongoing',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 26,
            testbedId: 7,
            assignedEmployeeId: 8,
            status: 'queued',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 1,
            notes: 'Smart meter power quality analysis',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 28,
            testbedId: 7,
            assignedEmployeeId: 8,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 2,
            notes: null,
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Additional 4 tasks spread across test beds
        {
            serviceRequestId: 27,
            testbedId: 1,
            assignedEmployeeId: 2,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 4,
            notes: 'PCB assembly EMC tests',
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 29,
            testbedId: 2,
            assignedEmployeeId: 3,
            status: 'queued',
            priority: 'high',
            scheduledStartDate: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 5,
            notes: 'RF module additional EMC tests',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 21,
            testbedId: 3,
            assignedEmployeeId: 4,
            status: 'queued',
            priority: 'normal',
            scheduledStartDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 3,
            notes: 'Temperature sensor validation tests',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 20,
            testbedId: 7,
            assignedEmployeeId: 8,
            status: 'queued',
            priority: 'urgent',
            scheduledStartDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            scheduledEndDate: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            actualStartDate: null,
            actualEndDate: null,
            queuePosition: 3,
            notes: 'Urgent sensor array testing',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(testbedTasks).values(sampleTestbedTasks);

    // Status History - 12 records showing progression for 3-4 service requests
    const sampleStatusHistory = [
        // Service Request 33 (completed) - full progression
        {
            serviceRequestId: 33,
            status: 'requested',
            notes: 'Initial request received from client',
            changedBy: 'System',
            changedAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 33,
            status: 'replied',
            notes: 'Quotation sent to client',
            changedBy: 'Admin User',
            changedAt: new Date(Date.now() - 53 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 33,
            status: 'srf_filled',
            notes: 'Service request form filled and verified',
            changedBy: 'Admin User',
            changedAt: new Date(Date.now() - 52 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 33,
            status: 'agreed',
            notes: 'Client agreed to terms and pricing',
            changedBy: 'Admin User',
            changedAt: new Date(Date.now() - 51 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 33,
            status: 'material_received',
            notes: 'All samples received and verified against DC-2024-0225',
            changedBy: 'Lab Technician',
            changedAt: new Date(Date.now() - 49 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 33,
            status: 'testing',
            notes: 'Testing started on Test Bed 1',
            changedBy: 'Test Engineer',
            changedAt: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 33,
            status: 'completed',
            notes: 'All tests completed successfully, report delivered to client',
            changedBy: 'Test Engineer',
            changedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Service Request 26 (material_received) - partial progression
        {
            serviceRequestId: 26,
            status: 'requested',
            notes: 'Testing request submitted',
            changedBy: 'System',
            changedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 26,
            status: 'replied',
            notes: 'Quotation and timeline provided',
            changedBy: 'Sales Team',
            changedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 26,
            status: 'agreed',
            notes: 'Purchase order received from client',
            changedBy: 'Sales Team',
            changedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            serviceRequestId: 26,
            status: 'material_received',
            notes: 'Samples received in good condition - DC verified',
            changedBy: 'Receiving Department',
            changedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Service Request 22 (replied) - early stage
        {
            serviceRequestId: 22,
            status: 'requested',
            notes: 'High voltage testing request',
            changedBy: 'System',
            changedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(statusHistory).values(sampleStatusHistory);

    console.log('✅ Comprehensive test data seeder completed successfully');
    console.log('   - 15 service requests inserted (IDs starting from 19)');
    console.log('   - 23 testbed tasks inserted');
    console.log('   - 12 status history records inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});