import { db } from '@/db';
import { serviceRequests } from '@/db/schema';

async function main() {
    const now = Date.now();
    const dayInMs = 24 * 60 * 60 * 1000;
    
    const formatJobCardNumber = (daysAgo: number, sequence: string) => {
        const date = new Date(now - daysAgo * dayInMs);
        const year = date.getFullYear().toString().slice(-2);
        const month = (date.getMonth() + 1).toString().padStart(2, '0');
        const day = date.getDate().toString().padStart(2, '0');
        return `ARTL-RF-${year}${month}${day}-${sequence}-01-01`;
    };
    
    const formatDcNumber = (daysAgo: number, sequence: string) => {
        const date = new Date(now - daysAgo * dayInMs);
        const year = date.getFullYear().toString().slice(-2);
        const month = (date.getMonth() + 1).toString().padStart(2, '0');
        const day = date.getDate().toString().padStart(2, '0');
        return `DC-${year}${month}${day}-${sequence}`;
    };
    
    const getIsoDate = (daysAgo: number) => {
        return new Date(now - daysAgo * dayInMs).toISOString();
    };

    const sampleServiceRequests = [
        // REQUESTED STATUS (2 records)
        {
            jobCardNumber: formatJobCardNumber(2, '01'),
            companyId: 1,
            contactPersonId: 1,
            productName: 'IoT Gateway Module GW-5000',
            productDescription: 'Industrial IoT gateway with 4G LTE, WiFi, and Ethernet connectivity. Supports Modbus, MQTT, OPC-UA protocols.',
            quantity: 8,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Full EMC compliance testing per IEC 61000-6-2 and IEC 61000-6-4 standards. Radiated and conducted emissions required.',
            status: 'requested',
            requestedDate: getIsoDate(2),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Urgent client request - needs quotation within 24 hours',
            createdAt: getIsoDate(2),
            updatedAt: getIsoDate(2),
        },
        {
            jobCardNumber: formatJobCardNumber(3, '02'),
            companyId: 4,
            contactPersonId: 7,
            productName: 'Automotive Radar Sensor ARS-77G',
            productDescription: '77GHz FMCW radar sensor for ADAS applications. Long-range detection up to 250m.',
            quantity: 5,
            testType: 'Environmental Testing, EMC/EMI Testing',
            specialRequirements: 'Automotive EMC testing per CISPR 25, temperature cycling -40°C to +85°C per AEC-Q100',
            status: 'requested',
            requestedDate: getIsoDate(3),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Pre-production samples - automotive grade testing required',
            createdAt: getIsoDate(3),
            updatedAt: getIsoDate(3),
        },
        // REPLIED STATUS (2 records)
        {
            jobCardNumber: formatJobCardNumber(9, '03'),
            companyId: 3,
            contactPersonId: 5,
            productName: 'LED Driver Controller LDC-100W',
            productDescription: 'High-efficiency LED driver with dimming control, 100W output, 90-305VAC input',
            quantity: 12,
            testType: 'High Voltage Testing, EMC/EMI Testing',
            specialRequirements: 'Safety testing per IEC 61347-2-13, surge immunity testing 10kV per IEC 61000-4-5',
            status: 'replied',
            requestedDate: getIsoDate(9),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: `Quotation sent on ${getIsoDate(7).split('T')[0]}. Customer reviewing pricing and timeline.`,
            createdAt: getIsoDate(9),
            updatedAt: getIsoDate(7),
        },
        {
            jobCardNumber: formatJobCardNumber(10, '04'),
            companyId: 6,
            contactPersonId: 11,
            productName: 'Industrial Servo Drive ISD-5K',
            productDescription: '5kW AC servo drive controller with EtherCAT communication, 400VAC input',
            quantity: 4,
            testType: 'EMC/EMI Testing, High Voltage Testing',
            specialRequirements: 'IEC 61800-3 Category C2 EMC compliance, high voltage isolation testing 2.5kV',
            status: 'replied',
            requestedDate: getIsoDate(10),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Detailed test plan provided. Awaiting purchase order from customer.',
            createdAt: getIsoDate(10),
            updatedAt: getIsoDate(8),
        },
        // MATERIAL_RECEIVED STATUS (2 records)
        {
            jobCardNumber: formatJobCardNumber(22, '05'),
            companyId: 2,
            contactPersonId: 3,
            productName: 'Power Supply Unit PSU-24V-10A',
            productDescription: 'Industrial grade 240W power supply, 24VDC 10A output, universal AC input',
            quantity: 6,
            testType: 'High Voltage Testing, Environmental Testing',
            specialRequirements: 'Safety testing per IEC 60950-1, temperature testing 0°C to +50°C full load',
            status: 'material_received',
            requestedDate: getIsoDate(22),
            agreedDate: getIsoDate(20),
            materialReceivedDate: getIsoDate(17),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 5,
            assignedTestbedId: null,
            dcNumber: formatDcNumber(17, '045'),
            dcVerified: true,
            notes: 'All 6 units received in excellent condition. DC verified. Physical inspection passed. Awaiting test bed allocation.',
            createdAt: getIsoDate(22),
            updatedAt: getIsoDate(17),
        },
        {
            jobCardNumber: formatJobCardNumber(25, '06'),
            companyId: 7,
            contactPersonId: 13,
            productName: 'RF Transceiver Module RF-2.4G-BLE',
            productDescription: 'Bluetooth 5.2 Low Energy module with 2.4GHz RF transceiver, +8dBm output power',
            quantity: 20,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Bluetooth SIG qualification testing, FCC Part 15.247 compliance, radiated spurious emissions',
            status: 'material_received',
            requestedDate: getIsoDate(25),
            agreedDate: getIsoDate(23),
            materialReceivedDate: getIsoDate(19),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 2,
            assignedTestbedId: null,
            dcNumber: formatDcNumber(19, '038'),
            dcVerified: true,
            notes: 'All 20 modules received with antennas. DC matched. Preliminary power-up test successful. Scheduled for EMC chamber next week.',
            createdAt: getIsoDate(25),
            updatedAt: getIsoDate(19),
        },
        // TESTING STATUS (3 records)
        {
            jobCardNumber: formatJobCardNumber(35, '07'),
            companyId: 5,
            contactPersonId: 9,
            productName: 'Industrial Controller PLC-300',
            productDescription: 'Programmable Logic Controller with 32 I/O points, Modbus RTU/TCP, 24VDC powered',
            quantity: 3,
            testType: 'EMC/EMI Testing, Vibration Testing',
            specialRequirements: 'IEC 61131-2 PLC EMC testing, conducted immunity per IEC 61000-4-6, vibration per IEC 60068-2-6',
            status: 'testing',
            requestedDate: getIsoDate(35),
            agreedDate: getIsoDate(33),
            materialReceivedDate: getIsoDate(30),
            testingStartDate: getIsoDate(3),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 3,
            assignedTestbedId: 1,
            dcNumber: formatDcNumber(30, '029'),
            dcVerified: true,
            notes: 'EMC testing in progress. Conducted emissions completed - PASSED. Currently running radiated emissions sweep. 60% complete.',
            createdAt: getIsoDate(35),
            updatedAt: getIsoDate(3),
        },
        {
            jobCardNumber: formatJobCardNumber(38, '08'),
            companyId: 1,
            contactPersonId: 2,
            productName: 'Temperature Sensor Array TSA-8CH',
            productDescription: '8-channel RTD temperature sensor module, -50°C to +200°C range, 4-20mA output',
            quantity: 10,
            testType: 'Environmental Testing',
            specialRequirements: 'Temperature cycling -40°C to +85°C per IEC 60068-2-14, humidity testing 95% RH per IEC 60068-2-78',
            status: 'testing',
            requestedDate: getIsoDate(38),
            agreedDate: getIsoDate(36),
            materialReceivedDate: getIsoDate(33),
            testingStartDate: getIsoDate(2),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 4,
            assignedTestbedId: 2,
            dcNumber: formatDcNumber(33, '024'),
            dcVerified: true,
            notes: 'Thermal cycling test started. Completed 15 cycles out of 100. All sensors functioning within spec. Test continues.',
            createdAt: getIsoDate(38),
            updatedAt: getIsoDate(2),
        },
        {
            jobCardNumber: formatJobCardNumber(40, '09'),
            companyId: 4,
            contactPersonId: 8,
            productName: 'Motor Drive Inverter MDI-15K',
            productDescription: '15kW three-phase motor drive inverter, 400VAC input, vector control',
            quantity: 2,
            testType: 'High Voltage Testing, EMC/EMI Testing',
            specialRequirements: 'High voltage isolation 4kV per IEC 61800-5-1, EMC per IEC 61800-3 Category C3',
            status: 'testing',
            requestedDate: getIsoDate(40),
            agreedDate: getIsoDate(38),
            materialReceivedDate: getIsoDate(35),
            testingStartDate: getIsoDate(3),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 6,
            assignedTestbedId: 3,
            dcNumber: formatDcNumber(35, '021'),
            dcVerified: true,
            notes: 'High voltage insulation testing ongoing. Hipot test at 4.5kV - PASSED. Ground continuity test - PASSED. Dielectric withstand in progress.',
            createdAt: getIsoDate(40),
            updatedAt: getIsoDate(3),
        },
        // COMPLETED STATUS (2 records)
        {
            jobCardNumber: formatJobCardNumber(65, '10'),
            companyId: 3,
            contactPersonId: 6,
            productName: 'Smart Energy Meter SEM-3P',
            productDescription: 'Three-phase smart meter with WiFi/4G connectivity, bi-directional metering, 100A CT',
            quantity: 8,
            testType: 'EMC/EMI Testing, Environmental Testing',
            specialRequirements: 'IEC 62052-11 meter accuracy testing, EMC per IEC 61326-1, temperature -25°C to +70°C',
            status: 'completed',
            requestedDate: getIsoDate(65),
            agreedDate: getIsoDate(63),
            materialReceivedDate: getIsoDate(60),
            testingStartDate: getIsoDate(57),
            testingEndDate: getIsoDate(32),
            completionDate: getIsoDate(31),
            assignedEmployeeId: 1,
            assignedTestbedId: null,
            dcNumber: formatDcNumber(60, '015'),
            dcVerified: true,
            notes: 'All testing completed successfully. Accuracy tests PASSED within ±0.5%. EMC compliance PASSED. Final report delivered to customer.',
            createdAt: getIsoDate(65),
            updatedAt: getIsoDate(31),
        },
        {
            jobCardNumber: formatJobCardNumber(70, '11'),
            companyId: 6,
            contactPersonId: 12,
            productName: 'Wireless Sensor Node WSN-IoT-V2',
            productDescription: 'Battery-powered wireless sensor with LoRaWAN, temperature/humidity/pressure sensors',
            quantity: 15,
            testType: 'EMC/EMI Testing, Environmental Testing',
            specialRequirements: 'LoRaWAN certification testing, RF performance per ETSI EN 300 220, IP67 rating verification',
            status: 'completed',
            requestedDate: getIsoDate(70),
            agreedDate: getIsoDate(68),
            materialReceivedDate: getIsoDate(65),
            testingStartDate: getIsoDate(62),
            testingEndDate: getIsoDate(36),
            completionDate: getIsoDate(35),
            assignedEmployeeId: 7,
            assignedTestbedId: null,
            dcNumber: formatDcNumber(65, '012'),
            dcVerified: true,
            notes: 'Complete test cycle finished. LoRaWAN certification PASSED. RF range test exceeded 10km. IP67 submersion test PASSED. Customer satisfied with results.',
            createdAt: getIsoDate(70),
            updatedAt: getIsoDate(35),
        },
    ];

    await db.insert(serviceRequests).values(sampleServiceRequests);
    
    console.log('✅ Service requests comprehensive seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});