import { db } from '@/db';
import { serviceRequests } from '@/db/schema';

async function main() {
    const now = new Date();
    
    // Helper function to subtract days from current date
    const daysAgo = (days: number): string => {
        const date = new Date(now);
        date.setDate(date.getDate() - days);
        return date.toISOString();
    };
    
    // Helper function to format job card number
    const formatJobCard = (date: string, sequence: number): string => {
        const d = new Date(date);
        const year = d.getFullYear().toString().slice(-2);
        const month = String(d.getMonth() + 1).padStart(2, '0');
        const day = String(d.getDate()).padStart(2, '0');
        const seq = String(sequence).padStart(2, '0');
        return `ARTL-RF-${year}${month}${day}-${seq}-01-01`;
    };
    
    // Helper function to format DC number
    const formatDCNumber = (date: string, sequence: number): string => {
        const d = new Date(date);
        const year = d.getFullYear().toString().slice(-2);
        const month = String(d.getMonth() + 1).padStart(2, '0');
        const day = String(d.getDate()).padStart(2, '0');
        const seq = String(sequence).padStart(3, '0');
        return `DC-${year}${month}${day}-${seq}`;
    };

    const sampleServiceRequests = [
        // IDs 19-20: status='requested' (last 3 days)
        {
            jobCardNumber: formatJobCard(daysAgo(2), 19),
            companyId: 1,
            contactPersonId: 1,
            productName: '5G RF Power Amplifier Module',
            productDescription: 'High-power RF amplifier for 5G base station applications, 3.5 GHz band',
            quantity: 15,
            testType: 'RF Performance Testing',
            specialRequirements: 'Testing as per IEC 62368-1 and 3GPP TS 38.101 standards. Require environmental chamber testing at -40°C to +85°C.',
            status: 'requested',
            requestedDate: daysAgo(2),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Initial service request received. Awaiting technical review.',
            createdAt: daysAgo(2),
            updatedAt: daysAgo(2),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(1), 20),
            companyId: 3,
            contactPersonId: 5,
            productName: 'Industrial IoT Gateway',
            productDescription: 'Multi-protocol IoT gateway with cellular, WiFi, and Ethernet connectivity',
            quantity: 8,
            testType: 'EMC Testing',
            specialRequirements: 'Full EMC compliance testing per IEC 61000-6-2 and IEC 61000-6-4. Include conducted and radiated emissions/immunity tests.',
            status: 'requested',
            requestedDate: daysAgo(1),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Urgent priority request. Customer requires results within 3 weeks.',
            createdAt: daysAgo(1),
            updatedAt: daysAgo(1),
        },
        
        // IDs 21-22: status='replied' (last 7-10 days)
        {
            jobCardNumber: formatJobCard(daysAgo(9), 21),
            companyId: 2,
            contactPersonId: 3,
            productName: 'Automotive Radar Sensor',
            productDescription: '77 GHz FMCW radar sensor for autonomous driving applications',
            quantity: 12,
            testType: 'Automotive Electronics Testing',
            specialRequirements: 'Testing per ISO 26262 functional safety and CISPR 25 automotive EMC standards. Temperature cycling required.',
            status: 'replied',
            requestedDate: daysAgo(9),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Quotation sent to customer. Estimated testing duration: 4 weeks. Cost: ₹2,85,000.',
            createdAt: daysAgo(9),
            updatedAt: daysAgo(8),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(7), 22),
            companyId: 5,
            contactPersonId: 9,
            productName: 'Medical Grade Power Supply',
            productDescription: '300W isolated AC-DC power supply for medical imaging equipment',
            quantity: 20,
            testType: 'Medical Device Safety Testing',
            specialRequirements: 'IEC 60601-1 medical safety testing including leakage current, insulation resistance, and EMC per IEC 60601-1-2.',
            status: 'replied',
            requestedDate: daysAgo(7),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Detailed test plan and quotation provided. Awaiting customer approval and PO.',
            createdAt: daysAgo(7),
            updatedAt: daysAgo(7),
        },
        
        // IDs 23-24: status='srf_filled' (last 10-15 days)
        {
            jobCardNumber: formatJobCard(daysAgo(14), 23),
            companyId: 4,
            contactPersonId: 7,
            productName: 'LED Driver Controller IC',
            productDescription: 'High-efficiency LED driver IC for automotive lighting applications',
            quantity: 25,
            testType: 'Semiconductor Reliability Testing',
            specialRequirements: 'AEC-Q100 automotive qualification testing including thermal cycling, HTOL, and ESD per JEDEC standards.',
            status: 'srf_filled',
            requestedDate: daysAgo(14),
            agreedDate: daysAgo(12),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Service Request Form completed and signed. PO received. Awaiting material delivery.',
            createdAt: daysAgo(14),
            updatedAt: daysAgo(11),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(11), 24),
            companyId: 6,
            contactPersonId: 11,
            productName: 'Wireless Charging Pad',
            productDescription: '15W Qi-certified wireless charging pad with foreign object detection',
            quantity: 10,
            testType: 'Wireless Power Transfer Testing',
            specialRequirements: 'Qi v1.3 compliance testing per WPC specifications. Include efficiency, interoperability, and safety testing.',
            status: 'srf_filled',
            requestedDate: daysAgo(11),
            agreedDate: daysAgo(10),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'SRF approved. Customer to ship samples within 2 days. Expected delivery by courier.',
            createdAt: daysAgo(11),
            updatedAt: daysAgo(10),
        },
        
        // IDs 25-27: status='agreed' (last 15-20 days)
        {
            jobCardNumber: formatJobCard(daysAgo(19), 25),
            companyId: 7,
            contactPersonId: 13,
            productName: 'Smart Home Hub',
            productDescription: 'Multi-protocol smart home gateway with Zigbee, Z-Wave, and Matter support',
            quantity: 18,
            testType: 'IoT Protocol Compliance Testing',
            specialRequirements: 'Matter 1.1 certification testing and interoperability testing with major smart home devices. Include security assessment.',
            status: 'agreed',
            requestedDate: daysAgo(19),
            agreedDate: daysAgo(17),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Terms agreed. Samples in transit. Tracking number provided by customer.',
            createdAt: daysAgo(19),
            updatedAt: daysAgo(17),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(17), 26),
            companyId: 1,
            contactPersonId: 2,
            productName: 'Industrial Ethernet Switch',
            productDescription: '24-port managed Ethernet switch for industrial automation',
            quantity: 6,
            testType: 'Network Performance Testing',
            specialRequirements: 'IEEE 802.3 compliance, IEC 61850-3 industrial network testing, and vibration testing per IEC 60068-2-6.',
            status: 'agreed',
            requestedDate: daysAgo(17),
            agreedDate: daysAgo(16),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Agreement finalized. Material expected within 3 business days.',
            createdAt: daysAgo(17),
            updatedAt: daysAgo(16),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(15), 27),
            companyId: 3,
            contactPersonId: 6,
            productName: 'Battery Management System',
            productDescription: 'Li-ion battery management system for electric vehicle applications',
            quantity: 14,
            testType: 'Battery Safety Testing',
            specialRequirements: 'UN 38.3 transportation testing, IEC 62133 battery safety, and thermal runaway testing per UL 2580.',
            status: 'agreed',
            requestedDate: daysAgo(15),
            agreedDate: daysAgo(15),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Fast-track approval. Customer arranging hand delivery of samples tomorrow.',
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        
        // IDs 28-30: status='material_received' (last 20-30 days)
        {
            jobCardNumber: formatJobCard(daysAgo(28), 28),
            companyId: 2,
            contactPersonId: 4,
            productName: 'Satellite Communication Modem',
            productDescription: 'L-band satellite modem for maritime and aviation applications',
            quantity: 9,
            testType: 'Satellite Communication Testing',
            specialRequirements: 'RTCA DO-160G avionics testing including temperature, altitude, vibration, and EMI per aviation standards.',
            status: 'material_received',
            requestedDate: daysAgo(28),
            agreedDate: daysAgo(26),
            materialReceivedDate: daysAgo(23),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 2,
            assignedTestbedId: null,
            dcNumber: formatDCNumber(daysAgo(23), 28),
            dcVerified: true,
            notes: 'All samples received and verified. Physical inspection completed. Assigned to RF team for test planning.',
            createdAt: daysAgo(28),
            updatedAt: daysAgo(23),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(25), 29),
            companyId: 5,
            contactPersonId: 10,
            productName: 'Industrial PLC Module',
            productDescription: 'Programmable Logic Controller module for factory automation',
            quantity: 12,
            testType: 'Industrial Control Testing',
            specialRequirements: 'IEC 61131-2 PLC testing, environmental testing per IEC 60068, and EMC testing per IEC 61000-6-2/4.',
            status: 'material_received',
            requestedDate: daysAgo(25),
            agreedDate: daysAgo(24),
            materialReceivedDate: daysAgo(21),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 3,
            assignedTestbedId: null,
            dcNumber: formatDCNumber(daysAgo(21), 29),
            dcVerified: true,
            notes: 'Material received in good condition. DC verified and logged. Awaiting testbed allocation.',
            createdAt: daysAgo(25),
            updatedAt: daysAgo(21),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(22), 30),
            companyId: 4,
            contactPersonId: 8,
            productName: 'USB-C Power Delivery Controller',
            productDescription: 'USB-C PD 3.1 controller supporting up to 240W power delivery',
            quantity: 22,
            testType: 'USB Compliance Testing',
            specialRequirements: 'USB-IF compliance testing for USB4 and USB PD 3.1. Include interoperability testing with various chargers and devices.',
            status: 'material_received',
            requestedDate: daysAgo(22),
            agreedDate: daysAgo(21),
            materialReceivedDate: daysAgo(20),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 1,
            assignedTestbedId: null,
            dcNumber: formatDCNumber(daysAgo(20), 30),
            dcVerified: true,
            notes: 'All 22 units received and inspected. DC matched. Engineer assigned. Test schedule being prepared.',
            createdAt: daysAgo(22),
            updatedAt: daysAgo(20),
        },
        
        // IDs 31-33: status='testing' (last 30-45 days)
        {
            jobCardNumber: formatJobCard(daysAgo(42), 31),
            companyId: 6,
            contactPersonId: 12,
            productName: 'RFID Reader Module',
            productDescription: 'UHF RFID reader module for retail inventory management',
            quantity: 16,
            testType: 'RFID Performance Testing',
            specialRequirements: 'EPC Gen2v2 compliance testing, read range optimization, and FCC Part 15 regulatory testing.',
            status: 'testing',
            requestedDate: daysAgo(42),
            agreedDate: daysAgo(40),
            materialReceivedDate: daysAgo(37),
            testingStartDate: daysAgo(34),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 4,
            assignedTestbedId: 2,
            dcNumber: formatDCNumber(daysAgo(37), 31),
            dcVerified: true,
            notes: 'Testing in progress. Preliminary read range tests completed. EMC testing scheduled for next week.',
            createdAt: daysAgo(42),
            updatedAt: daysAgo(33),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(38), 32),
            companyId: 7,
            contactPersonId: 14,
            productName: 'Solar Inverter Controller',
            productDescription: 'Grid-tied solar inverter controller with anti-islanding protection',
            quantity: 7,
            testType: 'Solar Inverter Testing',
            specialRequirements: 'IEC 62109 safety testing, IEEE 1547 grid interconnection testing, and efficiency testing per CEC standards.',
            status: 'testing',
            requestedDate: daysAgo(38),
            agreedDate: daysAgo(37),
            materialReceivedDate: daysAgo(35),
            testingStartDate: daysAgo(32),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 5,
            assignedTestbedId: 3,
            dcNumber: formatDCNumber(daysAgo(35), 32),
            dcVerified: true,
            notes: 'Active testing phase. Grid simulation tests ongoing. Anti-islanding tests completed successfully.',
            createdAt: daysAgo(38),
            updatedAt: daysAgo(31),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(35), 33),
            companyId: 1,
            contactPersonId: 1,
            productName: 'Bluetooth 5.3 Audio Module',
            productDescription: 'Low-latency Bluetooth audio module with LC3 codec support',
            quantity: 28,
            testType: 'Bluetooth Qualification Testing',
            specialRequirements: 'Bluetooth SIG qualification testing for BT 5.3 and LE Audio. Include audio quality testing and range measurements.',
            status: 'testing',
            requestedDate: daysAgo(35),
            agreedDate: daysAgo(34),
            materialReceivedDate: daysAgo(33),
            testingStartDate: daysAgo(30),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 2,
            assignedTestbedId: 1,
            dcNumber: formatDCNumber(daysAgo(33), 33),
            dcVerified: true,
            notes: 'RF testing phase. Protocol compliance tests passed. Audio quality measurements in progress.',
            createdAt: daysAgo(35),
            updatedAt: daysAgo(30),
        },
        
        // IDs 34-35: status='completed' (last 45-60 days)
        {
            jobCardNumber: formatJobCard(daysAgo(58), 34),
            companyId: 3,
            contactPersonId: 5,
            productName: 'EV Charging Station Controller',
            productDescription: 'Level 2 EV charging station controller with OCPP 2.0.1 support',
            quantity: 5,
            testType: 'EV Charging Infrastructure Testing',
            specialRequirements: 'IEC 61851 EVSE testing, OCPP protocol compliance, and safety testing per UL 2594.',
            status: 'completed',
            requestedDate: daysAgo(58),
            agreedDate: daysAgo(56),
            materialReceivedDate: daysAgo(54),
            testingStartDate: daysAgo(51),
            testingEndDate: daysAgo(47),
            completionDate: daysAgo(46),
            assignedEmployeeId: 3,
            assignedTestbedId: 4,
            dcNumber: formatDCNumber(daysAgo(54), 34),
            dcVerified: true,
            notes: 'Testing completed successfully. All safety and protocol tests passed. Test report generated and reviewed.',
            createdAt: daysAgo(58),
            updatedAt: daysAgo(46),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(52), 35),
            companyId: 2,
            contactPersonId: 3,
            productName: 'LTE-M IoT Module',
            productDescription: 'LTE-M cellular IoT module with global band support',
            quantity: 30,
            testType: 'Cellular IoT Testing',
            specialRequirements: '3GPP TS 36.521 conformance testing, GCF certification testing, and carrier acceptance testing for major operators.',
            status: 'completed',
            requestedDate: daysAgo(52),
            agreedDate: daysAgo(51),
            materialReceivedDate: daysAgo(49),
            testingStartDate: daysAgo(46),
            testingEndDate: daysAgo(48),
            completionDate: daysAgo(47),
            assignedEmployeeId: 1,
            assignedTestbedId: 2,
            dcNumber: formatDCNumber(daysAgo(49), 35),
            dcVerified: true,
            notes: 'Full test cycle completed. Protocol conformance verified. Carrier interoperability tests passed.',
            createdAt: daysAgo(52),
            updatedAt: daysAgo(47),
        },
        
        // ID 36: status='reported' (last 60-75 days)
        {
            jobCardNumber: formatJobCard(daysAgo(72), 36),
            companyId: 5,
            contactPersonId: 9,
            productName: 'Industrial Temperature Sensor',
            productDescription: 'High-precision RTD temperature sensor for process control',
            quantity: 20,
            testType: 'Sensor Calibration Testing',
            specialRequirements: 'IEC 60751 Class A RTD testing, NIST-traceable calibration, and environmental testing per IEC 60068.',
            status: 'reported',
            requestedDate: daysAgo(72),
            agreedDate: daysAgo(70),
            materialReceivedDate: daysAgo(68),
            testingStartDate: daysAgo(65),
            testingEndDate: daysAgo(62),
            completionDate: daysAgo(61),
            assignedEmployeeId: 4,
            assignedTestbedId: 5,
            dcNumber: formatDCNumber(daysAgo(68), 36),
            dcVerified: true,
            notes: 'Final test report delivered to customer. All sensors met Class A specifications. Calibration certificates issued.',
            createdAt: daysAgo(72),
            updatedAt: daysAgo(60),
        },
    ];

    await db.insert(serviceRequests).values(sampleServiceRequests);
    
    console.log('✅ Service requests bulk seeder completed successfully - 18 records (IDs 19-36) inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});