import { db } from '@/db';
import { serviceRequests } from '@/db/schema';

async function main() {
    const now = new Date();
    const daysAgo = (days: number) => {
        const date = new Date(now);
        date.setDate(date.getDate() - days);
        return date;
    };

    const formatJobCard = (date: Date, sequence: number) => {
        const year = date.getFullYear().toString().slice(-2);
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        const seq = String(sequence).padStart(2, '0');
        return `ARTL-RF-${year}${month}${day}-${seq}-01-01`;
    };

    const formatDC = (date: Date, sequence: number) => {
        const year = date.getFullYear().toString().slice(-2);
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        const seq = String(sequence).padStart(3, '0');
        return `DC-${year}${month}${day}-${seq}`;
    };

    const sampleServiceRequests = [
        // REQUESTED (2) - Last 5 days
        {
            jobCardNumber: formatJobCard(daysAgo(2), 1),
            companyId: 1,
            contactPersonId: 1,
            productName: 'PCB Assembly Board',
            productDescription: '4-layer PCB with SMD components for automotive application',
            quantity: 15,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Testing required as per ISO 11452-2 standards',
            status: 'requested',
            requestedDate: daysAgo(2).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Client requested urgent testing for new automotive project. Initial review completed.',
            createdAt: daysAgo(2).toISOString(),
            updatedAt: daysAgo(2).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(4), 2),
            companyId: 3,
            contactPersonId: 5,
            productName: 'IoT Sensor Module',
            productDescription: 'Temperature and humidity sensor module with BLE connectivity',
            quantity: 25,
            testType: 'Environmental Testing',
            specialRequirements: 'Temperature range -20°C to 85°C, humidity 0-95% RH',
            status: 'requested',
            requestedDate: daysAgo(4).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Environmental chamber booking required. Awaiting quotation approval.',
            createdAt: daysAgo(4).toISOString(),
            updatedAt: daysAgo(4).toISOString(),
        },
        // REPLIED (2) - Last 10 days
        {
            jobCardNumber: formatJobCard(daysAgo(8), 3),
            companyId: 2,
            contactPersonId: 3,
            productName: 'Power Supply Unit',
            productDescription: '24V 5A SMPS with universal input voltage',
            quantity: 10,
            testType: 'High Voltage Testing',
            specialRequirements: 'Safety testing as per IEC 60950-1',
            status: 'replied',
            requestedDate: daysAgo(8).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Quotation sent with 2-week turnaround time. Awaiting client confirmation.',
            createdAt: daysAgo(8).toISOString(),
            updatedAt: daysAgo(7).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(9), 4),
            companyId: 5,
            contactPersonId: 9,
            productName: 'LED Driver Circuit',
            productDescription: 'Constant current LED driver for street lighting application',
            quantity: 20,
            testType: 'Thermal Testing',
            specialRequirements: 'Thermal imaging and load testing required',
            status: 'replied',
            requestedDate: daysAgo(9).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Detailed test plan shared with client. Discussing additional test parameters.',
            createdAt: daysAgo(9).toISOString(),
            updatedAt: daysAgo(8).toISOString(),
        },
        // SRF_FILLED (2) - Last 15 days
        {
            jobCardNumber: formatJobCard(daysAgo(13), 5),
            companyId: 4,
            contactPersonId: 7,
            productName: 'Microcontroller Board',
            productDescription: 'ARM Cortex-M4 based development board with multiple peripherals',
            quantity: 8,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Radiated and conducted emissions testing required',
            status: 'srf_filled',
            requestedDate: daysAgo(13).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'SRF form completed and submitted. Awaiting final commercial agreement.',
            createdAt: daysAgo(13).toISOString(),
            updatedAt: daysAgo(12).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(14), 6),
            companyId: 6,
            contactPersonId: 11,
            productName: 'Battery Management System',
            productDescription: 'Li-ion battery management system for electric vehicle',
            quantity: 12,
            testType: 'Vibration Testing',
            specialRequirements: 'Automotive grade vibration profile as per ISO 16750-3',
            status: 'srf_filled',
            requestedDate: daysAgo(14).toISOString(),
            agreedDate: null,
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'All documentation received. Purchase order expected this week.',
            createdAt: daysAgo(14).toISOString(),
            updatedAt: daysAgo(13).toISOString(),
        },
        // AGREED (3) - Last 20 days
        {
            jobCardNumber: formatJobCard(daysAgo(17), 7),
            companyId: 7,
            contactPersonId: 13,
            productName: 'Wireless Communication Module',
            productDescription: 'WiFi and Bluetooth combo module for IoT applications',
            quantity: 30,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'FCC Part 15 and CE RED compliance testing',
            status: 'agreed',
            requestedDate: daysAgo(17).toISOString(),
            agreedDate: daysAgo(16).toISOString(),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Purchase order received. Awaiting sample dispatch from client facility.',
            createdAt: daysAgo(17).toISOString(),
            updatedAt: daysAgo(16).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(18), 8),
            companyId: 1,
            contactPersonId: 2,
            productName: 'Display Panel',
            productDescription: '7-inch TFT LCD display with capacitive touch',
            quantity: 5,
            testType: 'Drop Test',
            specialRequirements: 'Drop test from 1.5m height on concrete surface',
            status: 'agreed',
            requestedDate: daysAgo(18).toISOString(),
            agreedDate: daysAgo(17).toISOString(),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Testing schedule confirmed. Client arranging courier pickup.',
            createdAt: daysAgo(18).toISOString(),
            updatedAt: daysAgo(17).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(19), 9),
            companyId: 3,
            contactPersonId: 6,
            productName: 'Industrial IoT Gateway',
            productDescription: 'Edge computing gateway with multiple protocol support',
            quantity: 6,
            testType: 'Environmental Testing',
            specialRequirements: 'Extended temperature testing -40°C to 70°C',
            status: 'agreed',
            requestedDate: daysAgo(19).toISOString(),
            agreedDate: daysAgo(18).toISOString(),
            materialReceivedDate: null,
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: null,
            dcVerified: false,
            notes: 'Agreement signed. Material expected to arrive within 3-4 business days.',
            createdAt: daysAgo(19).toISOString(),
            updatedAt: daysAgo(18).toISOString(),
        },
        // MATERIAL_RECEIVED (3) - Last 30 days
        {
            jobCardNumber: formatJobCard(daysAgo(25), 10),
            companyId: 2,
            contactPersonId: 4,
            productName: 'Smart Meter PCB',
            productDescription: 'Single phase energy meter PCB with RF communication',
            quantity: 18,
            testType: 'Salt Spray Test',
            specialRequirements: 'Salt spray test for 48 hours as per ASTM B117',
            status: 'material_received',
            requestedDate: daysAgo(25).toISOString(),
            agreedDate: daysAgo(24).toISOString(),
            materialReceivedDate: daysAgo(22).toISOString(),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: formatDC(daysAgo(22), 101),
            dcVerified: true,
            notes: 'Material received and verified. Initial visual inspection completed. Scheduling test chamber.',
            createdAt: daysAgo(25).toISOString(),
            updatedAt: daysAgo(22).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(27), 11),
            companyId: 5,
            contactPersonId: 10,
            productName: 'Medical Device Controller',
            productDescription: 'Microcontroller-based medical device with LCD display',
            quantity: 10,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Medical device EMC testing as per IEC 60601-1-2',
            status: 'material_received',
            requestedDate: daysAgo(27).toISOString(),
            agreedDate: daysAgo(26).toISOString(),
            materialReceivedDate: daysAgo(23).toISOString(),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: formatDC(daysAgo(23), 102),
            dcVerified: true,
            notes: 'All units received in good condition. Preparing test setup and documentation.',
            createdAt: daysAgo(27).toISOString(),
            updatedAt: daysAgo(23).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(28), 12),
            companyId: 4,
            contactPersonId: 8,
            productName: 'Automotive ECU',
            productDescription: 'Electronic control unit for automotive applications',
            quantity: 7,
            testType: 'Thermal Testing',
            specialRequirements: 'Temperature cycling and thermal shock testing',
            status: 'material_received',
            requestedDate: daysAgo(28).toISOString(),
            agreedDate: daysAgo(27).toISOString(),
            materialReceivedDate: daysAgo(24).toISOString(),
            testingStartDate: null,
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: null,
            assignedTestbedId: null,
            dcNumber: formatDC(daysAgo(24), 103),
            dcVerified: true,
            notes: 'Material inspected and logged. Test engineer assigned for setup.',
            createdAt: daysAgo(28).toISOString(),
            updatedAt: daysAgo(24).toISOString(),
        },
        // TESTING (3) - Last 40 days
        {
            jobCardNumber: formatJobCard(daysAgo(35), 13),
            companyId: 6,
            contactPersonId: 12,
            productName: 'Power Inverter Module',
            productDescription: '1kW solar power inverter with MPPT controller',
            quantity: 4,
            testType: 'High Voltage Testing',
            specialRequirements: 'Insulation resistance and dielectric strength testing',
            status: 'testing',
            requestedDate: daysAgo(35).toISOString(),
            agreedDate: daysAgo(34).toISOString(),
            materialReceivedDate: daysAgo(32).toISOString(),
            testingStartDate: daysAgo(30).toISOString(),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 3,
            assignedTestbedId: 2,
            dcNumber: formatDC(daysAgo(32), 104),
            dcVerified: true,
            notes: 'Testing in progress. High voltage tests completed. Continuing with load testing.',
            createdAt: daysAgo(35).toISOString(),
            updatedAt: daysAgo(30).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(37), 14),
            companyId: 7,
            contactPersonId: 14,
            productName: 'RF Transceiver Board',
            productDescription: '2.4GHz RF transceiver module for wireless communication',
            quantity: 20,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Radiated emissions and receiver sensitivity testing',
            status: 'testing',
            requestedDate: daysAgo(37).toISOString(),
            agreedDate: daysAgo(36).toISOString(),
            materialReceivedDate: daysAgo(34).toISOString(),
            testingStartDate: daysAgo(31).toISOString(),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 5,
            assignedTestbedId: 4,
            dcNumber: formatDC(daysAgo(34), 105),
            dcVerified: true,
            notes: 'EMC chamber testing in progress. Conducted emissions test completed successfully.',
            createdAt: daysAgo(37).toISOString(),
            updatedAt: daysAgo(31).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(38), 15),
            companyId: 1,
            contactPersonId: 1,
            productName: 'Industrial Sensor Array',
            productDescription: 'Multi-sensor array for industrial automation',
            quantity: 15,
            testType: 'Vibration Testing',
            specialRequirements: 'Random vibration and sine sweep testing',
            status: 'testing',
            requestedDate: daysAgo(38).toISOString(),
            agreedDate: daysAgo(37).toISOString(),
            materialReceivedDate: daysAgo(35).toISOString(),
            testingStartDate: daysAgo(32).toISOString(),
            testingEndDate: null,
            completionDate: null,
            assignedEmployeeId: 7,
            assignedTestbedId: 6,
            dcNumber: formatDC(daysAgo(35), 106),
            dcVerified: true,
            notes: 'Vibration testing ongoing. Three axis testing in progress on shaker table.',
            createdAt: daysAgo(38).toISOString(),
            updatedAt: daysAgo(32).toISOString(),
        },
        // COMPLETED (2) - Last 50 days
        {
            jobCardNumber: formatJobCard(daysAgo(47), 16),
            companyId: 3,
            contactPersonId: 5,
            productName: 'Home Automation Hub',
            productDescription: 'Central hub for smart home automation with voice control',
            quantity: 12,
            testType: 'Environmental Testing',
            specialRequirements: 'Temperature humidity and thermal shock testing',
            status: 'completed',
            requestedDate: daysAgo(47).toISOString(),
            agreedDate: daysAgo(46).toISOString(),
            materialReceivedDate: daysAgo(44).toISOString(),
            testingStartDate: daysAgo(42).toISOString(),
            testingEndDate: daysAgo(38).toISOString(),
            completionDate: daysAgo(37).toISOString(),
            assignedEmployeeId: 2,
            assignedTestbedId: 3,
            dcNumber: formatDC(daysAgo(44), 107),
            dcVerified: true,
            notes: 'All testing completed successfully. Test report prepared and shared with client.',
            createdAt: daysAgo(47).toISOString(),
            updatedAt: daysAgo(37).toISOString(),
        },
        {
            jobCardNumber: formatJobCard(daysAgo(48), 17),
            companyId: 2,
            contactPersonId: 3,
            productName: 'EV Charging Station Controller',
            productDescription: 'Fast charging controller with CAN bus communication',
            quantity: 8,
            testType: 'High Voltage Testing',
            specialRequirements: 'Safety testing and surge immunity testing',
            status: 'completed',
            requestedDate: daysAgo(48).toISOString(),
            agreedDate: daysAgo(47).toISOString(),
            materialReceivedDate: daysAgo(45).toISOString(),
            testingStartDate: daysAgo(43).toISOString(),
            testingEndDate: daysAgo(39).toISOString(),
            completionDate: daysAgo(38).toISOString(),
            assignedEmployeeId: 4,
            assignedTestbedId: 1,
            dcNumber: formatDC(daysAgo(45), 108),
            dcVerified: true,
            notes: 'Testing completed as per IEC 61851-1. All units passed. Final report delivered.',
            createdAt: daysAgo(48).toISOString(),
            updatedAt: daysAgo(38).toISOString(),
        },
        // REPORTED (1) - Last 60 days
        {
            jobCardNumber: formatJobCard(daysAgo(58), 18),
            companyId: 5,
            contactPersonId: 9,
            productName: 'Industrial Router',
            productDescription: '4G LTE industrial router with VPN support',
            quantity: 10,
            testType: 'EMC/EMI Testing',
            specialRequirements: 'Full EMC testing for CE marking compliance',
            status: 'reported',
            requestedDate: daysAgo(58).toISOString(),
            agreedDate: daysAgo(57).toISOString(),
            materialReceivedDate: daysAgo(55).toISOString(),
            testingStartDate: daysAgo(53).toISOString(),
            testingEndDate: daysAgo(49).toISOString(),
            completionDate: daysAgo(48).toISOString(),
            assignedEmployeeId: 6,
            assignedTestbedId: 5,
            dcNumber: formatDC(daysAgo(55), 109),
            dcVerified: true,
            notes: 'Complete EMC test report issued. Client acknowledged receipt. Material ready for return.',
            createdAt: daysAgo(58).toISOString(),
            updatedAt: daysAgo(47).toISOString(),
        },
    ];

    await db.insert(serviceRequests).values(sampleServiceRequests);
    
    console.log('✅ Service requests seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});