import { db } from '@/db';
import { testbedTasks } from '@/db/schema';

async function main() {
    const now = new Date();
    const oneDayAgo = new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000);
    const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
    const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
    const fourDaysAgo = new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000);
    const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);

    const sampleTasks = [
        // Task 1: Test Bed 1 - In Progress
        {
            service_request_id: 13,
            testbed_id: 1,
            assigned_employee_id: 3,
            status: 'in_progress',
            priority: 'high',
            scheduled_start_date: fourDaysAgo.toISOString(),
            scheduled_end_date: new Date(fourDaysAgo.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: twoDaysAgo.toISOString(),
            actual_end_date: null,
            queue_position: 0,
            notes: 'Environmental stress screening test in progress',
            created_at: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: twoDaysAgo.toISOString(),
        },
        // Task 2: Test Bed 1 - Queued
        {
            service_request_id: 28,
            testbed_id: 1,
            assigned_employee_id: 5,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 1,
            notes: 'Thermal cycling test - awaiting test bed availability',
            created_at: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 3: Test Bed 1 - Queued
        {
            service_request_id: 29,
            testbed_id: 1,
            assigned_employee_id: 2,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 2,
            notes: 'Vibration testing for automotive components',
            created_at: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 4: Test Bed 2 - Queued
        {
            service_request_id: 30,
            testbed_id: 2,
            assigned_employee_id: 7,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 1,
            notes: 'EMC compliance testing scheduled',
            created_at: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 5: Test Bed 2 - Queued
        {
            service_request_id: 19,
            testbed_id: 2,
            assigned_employee_id: 4,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 2,
            notes: 'Radio frequency interference testing',
            created_at: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 6: Test Bed 2 - Queued
        {
            service_request_id: 20,
            testbed_id: 2,
            assigned_employee_id: 1,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 3,
            notes: 'Electromagnetic compatibility assessment',
            created_at: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 7: Test Bed 3 - In Progress
        {
            service_request_id: 14,
            testbed_id: 3,
            assigned_employee_id: 6,
            status: 'in_progress',
            priority: 'urgent',
            scheduled_start_date: fiveDaysAgo.toISOString(),
            scheduled_end_date: new Date(fiveDaysAgo.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: oneDayAgo.toISOString(),
            actual_end_date: null,
            queue_position: 0,
            notes: 'Urgent safety compliance testing for medical device',
            created_at: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: oneDayAgo.toISOString(),
        },
        // Task 8: Test Bed 3 - Queued
        {
            service_request_id: 21,
            testbed_id: 3,
            assigned_employee_id: 8,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 1,
            notes: 'Humidity chamber testing for electronics',
            created_at: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 9: Test Bed 5 - In Progress
        {
            service_request_id: 15,
            testbed_id: 5,
            assigned_employee_id: 2,
            status: 'in_progress',
            priority: 'urgent',
            scheduled_start_date: fiveDaysAgo.toISOString(),
            scheduled_end_date: new Date(fiveDaysAgo.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: threeDaysAgo.toISOString(),
            actual_end_date: null,
            queue_position: 0,
            notes: 'Critical load testing for industrial equipment',
            created_at: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: threeDaysAgo.toISOString(),
        },
        // Task 10: Test Bed 5 - Queued
        {
            service_request_id: 22,
            testbed_id: 5,
            assigned_employee_id: 5,
            status: 'queued',
            priority: 'urgent',
            scheduled_start_date: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 11 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 1,
            notes: 'High voltage isolation testing - urgent customer requirement',
            created_at: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 11: Test Bed 5 - Queued
        {
            service_request_id: 23,
            testbed_id: 5,
            assigned_employee_id: 3,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 11 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 2,
            notes: 'Power supply endurance testing',
            created_at: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 12: Test Bed 5 - Queued
        {
            service_request_id: 24,
            testbed_id: 5,
            assigned_employee_id: 7,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 23 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 3,
            notes: 'Mechanical stress testing for structural components',
            created_at: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 13: Test Bed 7 - In Progress
        {
            service_request_id: 31,
            testbed_id: 7,
            assigned_employee_id: 4,
            status: 'in_progress',
            priority: 'urgent',
            scheduled_start_date: threeDaysAgo.toISOString(),
            scheduled_end_date: new Date(threeDaysAgo.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: oneDayAgo.toISOString(),
            actual_end_date: null,
            queue_position: 0,
            notes: 'Accelerated life testing - critical customer deadline',
            created_at: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: oneDayAgo.toISOString(),
        },
        // Task 14: Test Bed 8 - Queued
        {
            service_request_id: 25,
            testbed_id: 8,
            assigned_employee_id: 1,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 9 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 1,
            notes: 'Temperature coefficient testing',
            created_at: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 15: Test Bed 1 - Queued
        {
            service_request_id: 26,
            testbed_id: 1,
            assigned_employee_id: 6,
            status: 'queued',
            priority: 'urgent',
            scheduled_start_date: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 19 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 3,
            notes: 'Urgent shock and vibration test for aerospace component',
            created_at: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 16: Test Bed 2 - Queued
        {
            service_request_id: 27,
            testbed_id: 2,
            assigned_employee_id: 8,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 24 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 4,
            notes: 'Conducted emissions testing for industrial controller',
            created_at: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 17: Test Bed 3 - Queued
        {
            service_request_id: 32,
            testbed_id: 3,
            assigned_employee_id: 2,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 2,
            notes: 'Salt spray corrosion testing',
            created_at: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 18: Test Bed 5 - Queued
        {
            service_request_id: 33,
            testbed_id: 5,
            assigned_employee_id: 5,
            status: 'queued',
            priority: 'urgent',
            scheduled_start_date: new Date(now.getTime() + 23 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 29 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 4,
            notes: 'Urgent dielectric strength testing',
            created_at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 19: Test Bed 7 - Queued
        {
            service_request_id: 34,
            testbed_id: 7,
            assigned_employee_id: 3,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 1,
            notes: 'Burn-in testing for semiconductor devices',
            created_at: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 20: Test Bed 8 - Queued
        {
            service_request_id: 35,
            testbed_id: 8,
            assigned_employee_id: 7,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 9 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 2,
            notes: 'Thermal shock testing for PCB assemblies',
            created_at: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 21: Test Bed 8 - Queued
        {
            service_request_id: 36,
            testbed_id: 8,
            assigned_employee_id: 4,
            status: 'queued',
            priority: 'low',
            scheduled_start_date: new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 3,
            notes: 'Routine calibration verification testing',
            created_at: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 22: Test Bed 1 - Queued
        {
            service_request_id: 11,
            testbed_id: 1,
            assigned_employee_id: 1,
            status: 'queued',
            priority: 'normal',
            scheduled_start_date: new Date(now.getTime() + 19 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 4,
            notes: 'Random vibration profile testing',
            created_at: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Task 23: Test Bed 7 - Queued
        {
            service_request_id: 12,
            testbed_id: 7,
            assigned_employee_id: 6,
            status: 'queued',
            priority: 'high',
            scheduled_start_date: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            scheduled_end_date: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            actual_start_date: null,
            actual_end_date: null,
            queue_position: 2,
            notes: 'HALT testing for consumer electronics',
            created_at: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            updated_at: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(testbedTasks).values(sampleTasks);

    console.log('✅ Test bed tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});